#version 430

float kernel_support ()
{
  return 4.0;
}

float k0 (float u)
{ 
  return ((.875 * u) * u + .125) * u;
}
float k1 (float u)
{ 
  return ((-2.625 * u + 2.625) * u + 2.25) * u + 1.0;
}
float k2 (float u)
{ 
  return ((2.625 * u - 5.25) * u + .375) * u + 3.25;
}
float k3 (float u)
{ 
  return ((-.875 * u + 2.625) * u - 2.75) * u + 1.0;
}

float kernel_weight (float x)
{
  x = abs(x);
  return x > 2.0 ? 0.0 : x > 1.0 ? k0(2.0 - x) : k1(1.0 - x);
}