#version 430

float kernel_support ()
{
  return 4.0;
}

float k0 (float u)
{ 
  return ((.5 * u - .5) * u) * u; 
}
float k1 (float u)
{ 
  return ((-1.5 * u + 2.0) * u + .5) * u; 
}
float k2 (float u)
{ 
  return ((1.5 * u - 2.5) * u) * u + 1.0;
}
float k3 (float u)
{ 
  return ((-0.5 * u + 1.0) * u - 0.5) * u;
}

float kernel_weight (float x)
{
  x = abs(x);
  return x > 2.0 ? 0.0 : x > 1.0 ? k0(2.0 - x) : k1(1.0 - x);
}